### ISSUE TITLE
rbac?

### ISSUE THREAD

**Issue by schmitch** [hjacobs/kube-job-cleaner#14]
does kube-job-cleaner already work with rbac enabled?
I tried it out, however since I didn't specified any service account or anything I always get:

```
Traceback (most recent call last):
  File "/cleaner.py", line 27, in <module>
    for job in pykube.Job.objects(api, namespace=pykube.all):
  File "/usr/lib/python3.5/site-packages/pykube/query.py", line 130, in __iter__
    return iter(self.query_cache["objects"])
  File "/usr/lib/python3.5/site-packages/pykube/query.py", line 120, in query_cache
    cache["response"] = self.execute().json()
  File "/usr/lib/python3.5/site-packages/pykube/query.py", line 105, in execute
    r.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.0.0.1:443/apis/batch/v1/jobs
```

**Comment by kball** [comment]
I ran into this same problem. @hjacobs what would I need to do to set up appropriate permissions?

**Comment by tomislater** [comment]
Solution:

**rbac.yaml** file:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-job-cleaner
  namespace: kube-job-cleaner

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-job-cleaner-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: kube-job-cleaner
  namespace: kube-job-cleaner
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: ""
```

**cronjob.yaml** file:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-job-cleaner
  namespace: kube-job-cleaner
  labels:
    application: kube-job-cleaner
    version: "0.1"
spec:
  schedule: "17 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            application: kube-job-cleaner
            version: "0.1"
        spec:
          serviceAccountName: kube-job-cleaner
          restartPolicy: OnFailure
          containers:
          - name: cleaner
            image: "hjacobs/kube-job-cleaner:0.7"
            resources:
              limits:
                cpu: 200m
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 50Mi
```

Deploy:

```
kubectl create namespace kube-job-cleaner
kubectl apply -f rbac.yaml
kubectl apply -f cronjob.yaml
```

**Comment by tomislater** [comment]
We can close this issue.
